import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {ClerkProvider} from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dentira-AI Powered Dental Assistent",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}
      >
      <ClerkProvider appearance={{
        variables:{
          colorPrimary: "#b05730",
          colorBackground: "#262624",
          colorText: "#f1f5f9",
          colorInputBackground: "#334155",
          colorTextSecondary: "#94a3b8",
         
        }
      }}>
        {children}
        </ClerkProvider>
      </body>
    </html>
  );
}
